"""
Rainwave Kodi Addon - Stream Player

This module provides the Player class which generates stream URLs for Rainwave stations.

IMPORTANT CLARIFICATION:
=======================

Despite the class name "Player", this module does NOT handle actual audio playback. Kodi's built-in player handles that. This class only generates the STREAM URLs that Kodi will play.

The name "Player" is somewhat misleading but is kept for historical reasons and consistency with the codebase.

KEY RESPONSIBILITY:
===================

The ONE critical job of this module is to generate stream URLs in a format that works correctly with Kodi's player, particularly handling the ICY metadata issue that was causing major problems.
"""

import xbmc
from .api import RainwaveAPI

#==STATION MAPPINGS================

'''
Station ID to URL slug mapping for stream URL generation

These slugs are used in the stream URLs: Format: https://relay.rainwave.cc/{slug}.mp3

Station IDs come from the Rainwave API and constants.py:
   1: Game
   2: OC Remix
   3: Covers
   4: Chiptune
   5: All
   6: Chill

Note: This duplicates the STATIONS dict in constants.py. Consider consolidating to a single location in a future refactor.
'''

STATIONS = {
    1: "game",
    2: "ocremix",
    3: "covers",
    4: "chiptune",
    5: "all",
    6: "chill",
}

class Player:
    """
    Provides stream URLs for Rainwave stations.

    This class contains the single most important method in the entire addon: get_stream_url(). Without the proper URL format generated by this method, the addon simply doesn't work correctly.

    ATTRIBUTES:
        api (RainwaveAPI): API client instance (passed but not heavily used)

    NOTE:
        The api attribute is passed to the constructor but is only used if this class needs to make API calls in the future. Currently, it's not used because stream URL generation is purely static.
    """
    
    def __init__(self, api):
        self.api = api

    def get_stream_url(self, sid):
        """
        Generate the stream URL for a Rainwave station.

        URL FORMAT:
        -----------
        https://relay.rainwave.cc/{station_slug}.mp3|Icy-MetaData=0

        Where {station_slug} is looked up from the STATIONS dict.

        THE CRITICAL SUFFIX:
        -------------------

        The '|Icy-MetaData=0' suffix is the SINGLE MOST IMPORTANT detail in the entire addon. Without it, the addon doesn't work correctly.

        WHAT HAPPENS WITHOUT Icy-MetaData=0:
        ===================================

        1. Kodi's player core reads the stream's embedded ICY metadata
           - The relay stream (relay.rainwave.cc) includes ICY metadata
           - This metadata contains the current song title
           - Kodi treats this as AUTHORITATIVE for the playing item

        2. Kodi overwrites our custom metadata
           - We set title/artist/album via setResolvedUrl()
           - Kodi sets title/artist/album from the ICY metadata
           - The ICY metadata WINS, overwriting ours almost immediately

        3. Only artwork survives
           - ICY metadata never carries artwork
           - So our setArt() calls still work
           - But title/artist/album are gone

        4. Remote apps see only first song
           - Kore (Kodi's remote) uses JSON-RPC Player.GetItem
           - This reads the info tag that ICY overwrote
           - Result: Only first song's artwork shows, never updates

        5. Every update loses the race
           - service.py polls API every 5 seconds
           - service.py calls updateInfoTag() with new metadata
           - Stream's ICY metadata arrives shortly after
           - ICY metadata overwrites our update
           - Result: Display never updates after first song

        WHAT HAPPENS WITH Icy-MetaData=0:
        ==================================

        1. Kodi's player core does NOT read ICY metadata
           - The suffix tells Kodi to ignore the stream's embedded metadata

        2. Our metadata is the only source
           - title/artist/album from setResolvedUrl() are preserved
           - artwork from setArt() is preserved
           - Updates from service.py's updateInfoTag() are preserved

        3. Remote apps see all metadata
           - JSON-RPC Player.GetItem shows our metadata
           - Kore and other remotes display correct info
           - Updates are visible to all clients

        4. Display stays in sync
           - Combined with SyncQueue, display matches audio
           - Progress bar works correctly
           - Everything updates as expected

        ARGS:
            sid (int): Station ID (1-6, see STATIONS dict)

        RETURNS:
            str: Full stream URL with ICY metadata disabled

        EXAMPLES:
            get_stream_url(1) -> "https://relay.rainwave.cc/game.mp3|Icy-MetaData=0"
            get_stream_url(5) -> "https://relay.rainwave.cc/all.mp3|Icy-MetaData=0"
        """
        
        return f"https://relay.rainwave.cc/{STATIONS[sid]}.mp3|Icy-MetaData=0"